export default function Terms() {
  return (
    <div className="pt-16">
      <section className="py-16 sm:py-24 px-6">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl sm:text-4xl font-bold mb-2">Terms of Service</h1>
          <p className="text-sm text-gray-500 mb-12">Effective: April 13, 2026</p>

          <div className="space-y-10 text-sm text-gray-400 leading-relaxed">

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">1. Agreement to Terms</h2>
              <p className="mb-3">
                These Terms of Service (&ldquo;Terms&rdquo;) are a legal agreement between you (&ldquo;you&rdquo; or &ldquo;User&rdquo;) and omnirun (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). They govern your access to and use of the omnirun desktop application, website (omnirun.app), APIs, documentation, and all related services (collectively, the &ldquo;Service&rdquo;).
              </p>
              <p>
                By downloading, installing, accessing, or using the Service, you agree to be bound by these Terms. If you are using the Service on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms. If you do not agree, do not access or use the Service.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">2. Definitions</h2>
              <p>
                &ldquo;Application&rdquo; means the omnirun desktop software available for macOS, Windows, and Linux. &ldquo;Content&rdquo; means any code, files, text, images, data, or other materials you create, upload, or generate through the Service. &ldquo;Inputs&rdquo; means prompts, instructions, files, or other content you provide to the AI features of the Service. &ldquo;Outputs&rdquo; means code, text, or other content generated by AI in response to your Inputs. &ldquo;API Keys&rdquo; means authentication credentials for third-party AI providers that you configure within the Application. &ldquo;Subscription&rdquo; means your paid plan for accessing the Service. &ldquo;Team&rdquo; means a group of users sharing access under Team, Business, or Enterprise plans.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">3. Eligibility</h2>
              <p>
                You must be at least 16 years of age to use the Service. If you are under 18, you represent that your parent or legal guardian has reviewed and agreed to these Terms on your behalf. If you are using the Service on behalf of an entity, you represent that you have the legal authority to bind that entity.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">4. Accounts</h2>
              <p className="mb-3">
                You must create an account to use the Service. You agree to provide accurate, current, and complete information and to keep your account information updated. You are solely responsible for maintaining the confidentiality of your credentials and for all activity under your account.
              </p>
              <p>
                You must notify us immediately at{" "}
                <a href="mailto:support@omnirun.app" className="transition-colors" style={{ color: "#2DB87A" }}>support@omnirun.app</a>{" "}
                if you suspect unauthorized access to your account. You may not create multiple accounts to circumvent plan limits, trial restrictions, or enforcement actions. We reserve the right to suspend or disable accounts that violate these Terms.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">5. Subscriptions, Billing, and Trials</h2>
              <p className="mb-3">
                <span className="text-white font-medium">Plans.</span> The Service is offered through paid subscription plans: Starter, Pro, Studio, Team, Business, and Enterprise. All prices are listed in Euros (&euro;). We reserve the right to modify pricing with at least 30 days&rsquo; prior notice. Changes will not affect your current billing period.
              </p>
              <p className="mb-3">
                <span className="text-white font-medium">Free Trial.</span> We may offer a free trial period. A valid payment method is required to begin a trial. If you do not cancel before the trial period ends, your selected plan will activate automatically and you will be charged. Trial terms may vary and are specified at the time of signup.
              </p>
              <p className="mb-3">
                <span className="text-white font-medium">Billing.</span> Subscriptions are billed in advance on a monthly or annual basis, depending on the plan you select. Payments are processed by Stripe. You authorize us to charge your payment method for recurring fees until you cancel. All fees are non-refundable except as required by applicable law.
              </p>
              <p className="mb-3">
                <span className="text-white font-medium">Cancellation.</span> You may cancel your subscription at any time through the Application&rsquo;s settings. Cancellation takes effect at the end of the current billing period. You retain access to paid features until that date. No partial refunds are provided for unused time.
              </p>
              <p>
                <span className="text-white font-medium">Plan Changes.</span> Upgrades take effect immediately with prorated charges. Downgrades take effect at the start of the next billing cycle.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">6. Bring Your Own Keys (BYOK)</h2>
              <p className="mb-3">
                The Service operates on a Bring Your Own Keys model. You provide your own API keys from third-party AI providers (such as Anthropic, OpenAI, or others). Your subscription covers the omnirun Application. AI usage costs are billed separately and directly by your chosen AI provider under their own terms.
              </p>
              <p>
                API Keys are stored locally on your device in encrypted form. For Team plans using shared API keys, encrypted keys are synced to our cloud backend. We do not have access to your decrypted API keys. You are solely responsible for the security, usage, costs, and compliance associated with your API Keys and third-party provider agreements.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">7. Your Content and Intellectual Property</h2>
              <p className="mb-3">
                <span className="text-white font-medium">Ownership.</span> You retain full ownership of all Content you create using the Service, including code, files, projects, and Outputs. We claim no ownership, license, or rights over your Content. What you build with omnirun is entirely yours.
              </p>
              <p className="mb-3">
                <span className="text-white font-medium">No Training on Your Data.</span> We do not use your Content, Inputs, or Outputs to train AI models or permit any third party to do so. Your project files, code, and AI conversations remain private and are not used for any purpose beyond providing the Service to you.
              </p>
              <p>
                <span className="text-white font-medium">Our IP.</span> The Application, website, brand, logos, documentation, and all associated intellectual property are owned by us and protected by applicable laws. These Terms do not grant you any rights to our trademarks or brand assets beyond what is necessary to use the Service.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">8. Local-First Architecture</h2>
              <p>
                The Application operates primarily on your local device. Your project files, source code, AI conversations, chat histories, and project memory are stored locally and are not uploaded to our servers. Only account-related data (profile information, subscription status, team membership, anonymized usage statistics) is synced to our cloud backend for authentication and service management purposes. If you uninstall the Application, your local data remains on your device unless you manually delete it.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">9. Acceptable Use</h2>
              <p className="mb-3">You agree not to use the Service to:</p>
              <p>
                Violate any applicable laws, regulations, or third-party rights; create, distribute, or deploy malware, viruses, or harmful software; gain unauthorized access to systems, networks, or data; generate illegal, abusive, harassing, defamatory, or discriminatory content; reverse-engineer, decompile, disassemble, or extract source code from the Application except as permitted by applicable law; resell, sublicense, or redistribute the Application without our written consent; circumvent plan limits, trial restrictions, or usage quotas through technical means; create multiple accounts to abuse promotions or evade enforcement; interfere with or disrupt the integrity, security, or performance of the Service; or use the Service in any manner that could damage, disable, or impair our infrastructure.
              </p>
              <p className="mt-3">
                We reserve the right to investigate violations and take appropriate action, including suspension or termination of your account.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">10. Third-Party Services</h2>
              <p>
                The Service integrates with third-party services including, but not limited to, Vercel, GitHub, Stripe, Supabase, Resend, Cloudflare, and various domain registrars and AI providers. Your use of these integrations is subject to the respective third-party&rsquo;s terms of service and privacy policies. We are not responsible for the availability, accuracy, or conduct of third-party services. Any data you share with third-party services through the Application is governed by those services&rsquo; own policies.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">11. Desktop and Browser Control</h2>
              <p>
                The Application includes features that can view and interact with your desktop and browser through screenshot capture and input simulation. Screenshots taken for this purpose are sent directly to the AI provider via their API for processing. We do not store, retain, or have access to these screenshots. Sensitive actions&mdash;including payments, password entry, form submissions, and social media posts&mdash;require your explicit approval before execution. You can stop any automated action immediately using the global kill switch. You are responsible for reviewing and approving all actions performed through these features.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">12. Team Plans</h2>
              <p>
                Team, Business, and Enterprise plans enable multiple users to collaborate on shared projects. The team owner is responsible for managing membership, permissions, billing, and ensuring all team members comply with these Terms. Each team member is individually bound by these Terms. The team owner is liable for activities conducted under the team account. Unlike solo plans, team project data is stored on our cloud backend (hosted on Supabase) to enable collaboration between team members. This includes project metadata, shared files, and team activity logs. Team data is protected by row-level security and encryption in transit.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">13. Template Marketplace</h2>
              <p>
                The Service may include a marketplace for project templates created by us or third-party creators. Templates are provided &ldquo;as is.&rdquo; While we scan templates for known security issues, we cannot guarantee that all templates are free from bugs, vulnerabilities, or malicious content. You are responsible for reviewing templates before use, particularly before deploying to production environments. We are not liable for damages resulting from the use of third-party templates.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">14. Beta and Early Access Features</h2>
              <p>
                We may offer features designated as beta, preview, or early access (&ldquo;Beta Features&rdquo;). Beta Features are provided for evaluation purposes and may be incomplete, unstable, or subject to change. We may modify, suspend, or discontinue Beta Features at any time without notice. Beta Features are provided &ldquo;as is&rdquo; without any warranty, and we shall have no liability arising from your use of Beta Features.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">15. Feedback</h2>
              <p>
                If you provide suggestions, ideas, or other feedback about the Service (&ldquo;Feedback&rdquo;), you grant us an unrestricted, irrevocable, perpetual, royalty-free license to use, modify, and incorporate that Feedback into the Service without any obligation to you. Feedback is voluntary and we are not required to implement any Feedback.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">16. Software Updates</h2>
              <p>
                We may release updates to the Application from time to time, including bug fixes, feature additions, and security patches. Updates may be installed automatically. Continued use of the Service following an update constitutes acceptance of the updated version. We recommend keeping the Application up to date.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">17. Disclaimers</h2>
              <p>
                THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE; THAT AI-GENERATED CODE OR CONTENT WILL BE ACCURATE, FUNCTIONAL, OR FREE FROM BUGS; THAT ANY PARTICULAR AI PROVIDER WILL REMAIN AVAILABLE OR COMPATIBLE; OR THAT INTEGRATIONS WITH THIRD-PARTY SERVICES WILL FUNCTION WITHOUT INTERRUPTION. YOU USE AI-GENERATED OUTPUT AT YOUR OWN RISK AND ARE RESPONSIBLE FOR REVIEWING, TESTING, AND VALIDATING ALL CODE AND CONTENT BEFORE USE.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">18. Limitation of Liability</h2>
              <p>
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, OMNIRUN AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, BUSINESS OPPORTUNITIES, GOODWILL, OR USE, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY. OUR TOTAL AGGREGATE LIABILITY FOR ANY CLAIMS ARISING UNDER THESE TERMS SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">19. Indemnification</h2>
              <p>
                You agree to indemnify, defend, and hold harmless omnirun and its officers, directors, employees, agents, and affiliates from and against any claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys&rsquo; fees) arising out of or related to: your use of the Service; your violation of these Terms; your violation of any third-party rights; Content you create or distribute using the Service; or your use of third-party API Keys and AI providers.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">20. Termination</h2>
              <p>
                We may suspend or terminate your account at any time if you violate these Terms or engage in conduct that we determine, in our reasonable discretion, to be harmful to the Service, other users, or third parties. Upon termination, your right to use the Service ceases immediately. Your local files and projects remain on your computer and are unaffected by account termination. You may delete your account at any time through the Application&rsquo;s settings. Sections 7, 15, 17, 18, 19, and 22 survive termination.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">21. Dispute Resolution</h2>
              <p className="mb-3">
                <span className="text-white font-medium">Informal Resolution.</span> Before filing a formal claim, you agree to attempt to resolve any dispute informally by contacting us at{" "}
                <a href="mailto:legal@omnirun.app" className="transition-colors" style={{ color: "#2DB87A" }}>legal@omnirun.app</a>. We will attempt to resolve the dispute within 30 days.
              </p>
              <p>
                <span className="text-white font-medium">Governing Law and Jurisdiction.</span> These Terms are governed by and construed in accordance with the laws of the Republic of Estonia. Any disputes that cannot be resolved informally shall be submitted to the exclusive jurisdiction of the courts in Tallinn, Estonia.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">22. General Provisions</h2>
              <p className="mb-3">
                <span className="text-white font-medium">Entire Agreement.</span> These Terms, together with the Privacy Policy and any additional terms referenced herein, constitute the entire agreement between you and omnirun regarding the Service and supersede all prior agreements and understandings.
              </p>
              <p className="mb-3">
                <span className="text-white font-medium">Severability.</span> If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions shall remain in full force and effect.
              </p>
              <p className="mb-3">
                <span className="text-white font-medium">Waiver.</span> Our failure to enforce any right or provision of these Terms shall not constitute a waiver of that right or provision.
              </p>
              <p className="mb-3">
                <span className="text-white font-medium">Assignment.</span> You may not assign or transfer these Terms without our prior written consent. We may assign these Terms in connection with a merger, acquisition, or sale of assets.
              </p>
              <p>
                <span className="text-white font-medium">Force Majeure.</span> We shall not be liable for any failure or delay in performing our obligations due to causes beyond our reasonable control, including natural disasters, war, terrorism, pandemics, power failures, internet disruptions, or actions of governmental authorities.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">23. Changes to These Terms</h2>
              <p>
                We may update these Terms from time to time. When we make material changes, we will update the &ldquo;Effective&rdquo; date at the top of this page and notify you via email or in-app notification at least 30 days before the changes take effect. Your continued use of the Service after the effective date constitutes acceptance of the revised Terms. If you do not agree to the changes, you must stop using the Service and cancel your subscription before the changes take effect.
              </p>
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white mb-3">24. Contact</h2>
              <p>
                If you have any questions about these Terms, please contact us at{" "}
                <a href="mailto:legal@omnirun.app" className="transition-colors" style={{ color: "#2DB87A" }}>
                  legal@omnirun.app
                </a>.
              </p>
            </div>

          </div>
        </div>
      </section>
    </div>
  );
}